### ISSUE TITLE
Comparison against Axios would be useful

### ISSUE THREAD

**Issue by Pyrolistical** [ksplatdev/AxleJS#1]
Axios has all the features Axle has and has been around longer. Would be helpful if you could give motivation on why Axle was created and why its better than Axios.

**Comment by ksplatdev** [comment]
> Axios has all the features Axle has and has been around longer. Would be helpful if you could give motivation on why Axle was created and why its better than Axios.

AxleJS was made as a fun little project to make fetch easier to use. AxleJS is more lightweight than Axios, and it has nearly the same features with AxleJS having a couple more than Axios. 

However￼, since Axios uses XHR, it can track file upload progress, but it does not support FormData.

**Comment by ksplatdev** [comment]
Fixed in staging.
