### ISSUE TITLE
Unusable in production due hardcoded status handling

### ISSUE THREAD

**Issue by Pyrolistical** [ksplatdev/AxleJS#2]
Due to https://github.com/ksplatdev/AxleJS/blob/main/src/utils/handleStatus.ts#L6 users of this library are unable to have custom handling of error status codes.

**Comment by ksplatdev** [comment]
How would you think it should be instead?

**Comment by Pyrolistical** [comment]
Checkout how Axios does it. it returns an error object with an optional response field if its an error that happened after the response was received https://github.com/axios/axios#handling-errors

**Comment by ksplatdev** [comment]
Commit <https://github.com/ksplatdev/AxleJS/commit/65d31889b826c016d3a4580fda08af12c840ff81> should fix this.

**Comment by ksplatdev** [comment]
[AxleJS Test on Codesandbox](https://codesandbox.io/s/axlejs-test-jjmdj?file=/src/index.js) has the build from that commit.
